###########################################################################
### Preflight Tasks :: Fetching Tools Required for Kafka Installation   ###
###########################################################################

- name: Kafka | Preflight | Ensure Required Packages
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  loop:
    - wget
    - unzip
    - tar
